### PR TITLE
Issue 512: Make Circle marker line color default to the fill color

### PR DESCRIPTION
**Pull request by adnanhemani**
[X] Wrote test for feature
[X] Added changes to CHANGELOG.md
[X] Bumped version number (delete if unneeded)

**Changes proposed:**
This will make map.Circle's default line color the fill color, if it is defined. Currently, we default to blue. Given that this feature is not well-documented, it is in the users' best interest to change the behavior to make the fill and line colors the same unless they are separately defined.

### CODE REVIEW

**Comment by adnanhemani** [comment]
Closes #512.

**Comment by adnanhemani** [comment]
Image of resulting change:

Screen Shot 2022-06-05 at 2 01 26 AM

**Comment by davidwagner** [comment]
The code looks reasonable to me, but after running tests locally, I get a bunch of failing tests.  e.g.,

```
__________________________ tests/Charts.ipynb::Cell 2 __________________________
Input:
t.group('yr').plot('yr')

AttributeError: module 'collections' has no attribute 'Iterable'
```

Looks like this needs to merge in the fix from 5258d45dd.  I can't remember how to do that in git...

Also:

```
______________________ tests/plotly-charts.ipynb::Cell 35 ______________________
Input:
t.select(['weight', 'displ', 'hp', 'accel']).scatter3d('weight', 'displ')

RuntimeError: scatter3d is a wrapper for iscatter3d and can only be called when interactive plots are enabled
```

and

```
______________________ tests/plotly-charts.ipynb::Cell 53 ______________________
Input:
t.with_column('weight-1000', t['weight']-1000).hist(['weight', 'weight-1000'], unit='kg', width=1000, height=500)

ValueError: Image size of 72000x36000 pixels is too large. It must be less than 2^16 in each direction.
```

and more.

**Comment by adnanhemani** [comment]
@davidwagner - I've merged the changes from `master` into this branch and the CI is now working! Please review and let me know if there's anything else we need from me :)

**Review by davidwagner — APPROVED** [review]

**Pull request merged**
