### PR TITLE
Hist labels

### PR DESCRIPTION
**Pull request by adnanhemani**
[No] Wrote test for feature
[X] Added changes in the Changelog section in README.md
[X] Bumped version number (delete if unneeded)

**Changes proposed:**
As per #347. Took Prof. DeNero's advice with adding the legacy printing options for numpy - and this seems to have fixed the issue being caused.

### CODE REVIEW

**Comment by adnanhemani** [comment]
Here's the before vs after pictures of the histograms.

Before:
Screen Shot 2019-06-18 at 1 11 26 PM

After:
Screen Shot 2019-06-18 at 1 11 46 PM

However, other than this, I'm not sure how else to test this change and see that this isn't adversely affecting anything else (we don't have testing for histograms). Any ideas? @davidwagner

**Comment by adnanhemani** [comment]
I'm requesting additional reviews for @papajohn and @ketozhang, since they are the originators of the issues to test this fix.

**Comment by davidwagner** [comment]
I'm unsure if this is the best fix.

It should be perfect for the Data 8 class.  From the perspective of the class, this seems like a great fix, as it will fix not only the histogram labels, but make other printed numbers look cleaner.

My one hesitation has to do with whether anyone is using the `datascience` library outside of Data 8.  If they are, `np.set_printoptions()` has global effects.  So, if someone else imports the `datascience` package for anything else, as a side effect it will change the formatting of everything printed using numpy.  Is that OK?  

Should we look into using matplotlib's `set_major_formatter` or `ticklabel_format`?  Or using numpy's `with np.printoptions():` syntax?  Or just go with this fix using `np.set_printoptions()` and see if anyone complains?  What do you think?

**Comment by adnanhemani** [comment]
> I'm unsure if this is the best fix.
> 
> It should be perfect for the Data 8 class. From the perspective of the class, this seems like a great fix, as it will fix not only the histogram labels, but make other printed numbers look cleaner.
> 
> My one hesitation has to do with whether anyone is using the `datascience` library outside of Data 8. If they are, `np.set_printoptions()` has global effects. So, if someone else imports the `datascience` package for anything else, as a side effect it will change the formatting of everything printed using numpy. Is that OK?
> 
> Should we look into using matplotlib's `set_major_formatter` or `ticklabel_format`? Or using numpy's `with np.printoptions():` syntax? Or just go with this fix using `np.set_printoptions()` and see if anyone complains? What do you think?

I thought about this too and thought that because this was the same setting that was present prior to np v1.13, that most everyone would be okay with it going back to that when using our library. But I think you're right - it's better to be defensive. So what I've done is wrapped the entire contents of `draw_hist` with the `with`-syntax (idk why the git diff is being so weird....) so that it uses the prior legacy version when making the histogram.

Did we ever see this with any other type of graph (scatter, boxplot, barplot, or anything else)? If so, I can wrap those easily too, but didn't want to make any changes to those functions prematurely.

**Pull request merged**
