### PR TITLE
Added docs for the method to_df()

### PR DESCRIPTION
**Pull request by vrii14**
[ ] Wrote test for feature
[ ] Added changes to CHANGELOG.md
[ ] Bumped version number (delete if unneeded)

**Changes proposed:**
Added the documentation for the method to_df() in the file tables.py

### CODE REVIEW

**Review by adnanhemani — CHANGES_REQUESTED** [review]
This looks great so far! Can you please add a type check in the docstring tests at the end of the current docstring to show that it's now definitely a Pandas DataFrame-type object? Thanks!

**Comment by vrii14** [comment]
Sure! I'll add the changes @adnanhemani

**Review by adnanhemani — APPROVED** [review]
LGTM! Thanks for this :)

**Comment by vrii14** [comment]
Thank you so much! It was my first Open Source Contribution!

**Pull request merged**
