### PR TITLE
Added docs for the method as_text()

### PR DESCRIPTION
**Pull request by vrii14**
[ ] Wrote test for feature
[ ] Added changes to CHANGELOG.md
[ ] Bumped version number (delete if unneeded)

**Changes proposed:**
Added documentation for the method as_text() with some examples as well

### CODE REVIEW

**Comment by vrii14** [comment]
Can't understand why are the builds failing.

**Comment by adnanhemani** [comment]
I've refreshed the cache and the tests shouldn't be failing anymore. Let's give it another try - please push a dummy change to tell Travis to rebuild this branch :)

**Comment by davidwagner** [comment]
The Travis build is failing with the error message: `ValueError: line 27 of the docstring for datascience.tables.Table.as_text has inconsistent leading whitespace: 'abc  | 12   | 5.5'`.  Can you look into that?  You might test your code with `make test` before submitting a pull request, to make sure all tests are passing.  Thank you!

**Comment by vrii14** [comment]
I tried fixing the inconsistent leading whitespace error in the second commit itself. But it's still showing the same. 
Can you please guide to how to test code earlier? And what is a _make test_

**Comment by vrii14** [comment]
Most probably the error is because of the "\n" which is in the output of the the method.
So to fix I can probably change "\n" to "\\n"(escape character with \n) but it will change the output of the example.
So should it be preferred?
Valid stackoverflow  thread [link](https://stackoverflow.com/questions/18772991/python-doctest-with-newline-characters-inconsistent-leading-whitespace-error)

**Comment by adnanhemani** [comment]
`make test` is the command you can use to run your tests locally.  And yes, using the actual escape character is ok for the doctest.

**Review by adnanhemani — APPROVED** [review]
LGTM - thanks for this!

**Pull request merged**
