### PR TITLE
Update read_table to pandas 0.42 read_csv

### PR DESCRIPTION
**Pull request by deculler**
[ X] Wrote test for feature
[ ] Added changes in the Changelog section in README.md
[ ] Bumped version number (delete if unneeded)

**Changes proposed:**
Updates read_table function to use pandas.read_csv rather than pandas.read_table, which was deprecated 0.24

### CODE REVIEW

**Comment by adnanhemani** [comment]
As I listed in #352 in more detail, I think it would be okay to not make this change (I would actually recommend against for readability purposes only) - it shouldn't affect our deployment on datahub and this deprecation looks like it'll be reversed in the next version of Pandas. If we still want to make this change, I think it should still be okay, though.

**Comment by adnanhemani** [comment]
Related to this, perhaps, we should lock down a fixed Pandas version number in our requirements.txt? I'm noticing that Pandas isn't even listed as a dependency that we rely on in our requirements.txt file - but as our library relies on it to import tables, we probably should have it listed.

**Comment by davidwagner** [comment]
@adnanhemani,  John says he doesn't want to list list pandas in the requirements.txt for datascience, as it causes surprising results when newcomers install datascience via pip.  We could list a version in the datahub config but maybe it's not needed.

**Comment by deculler** [comment]
The CVS reader and to/from dataframes is the full extent of the pandas
dependence.  This has protected us a lot from the many changes there.  We
could probably afford to special case the version in the code till it is
reversed, since it is only the one point. The warning is really distracting
to students and looks bad.  The other question is whether the python csv
reader has caught up.  Each used to fail on various different valid csv
files, but pandas was a little more robust.

**Comment by davidwagner** [comment]
I've merged #362, which is based on this, so this is now part of the library.  Thanks for the changes!

**Pull request closed without merging**
