### PR TITLE
Issue #163 - Documentation for stack method

### PR DESCRIPTION
**Pull request by SambhaviPD**
[ ] Wrote test for feature
[ ] Added changes to CHANGELOG.md
[ ] Bumped version number (delete if unneeded)

**Changes proposed:**
Added documentation for stack method, fixed build errors in my previous PR.

### CODE REVIEW

**Comment by SambhaviPD** [comment]
@adnanhemani - I corrected all build errors, still, 1 fails, though in my editor I see the same as expected in Travis build. Have attached a snapshot of the error. 
Anyways, looks like @CodTan has also submitted a PR for documentation on methods under transformation and that build was successful. I shall then close my PR. 

Screenshot 2020-10-07 114921

Not my day I guess :)

**Comment by adnanhemani** [comment]
Sorry about that! There's still plenty of other methods left to document, though! And an important new issue I've open on increasing our repo's test coverage here: #476. Thanks for contributing anyways!

**Comment by davidwagner** [comment]
@SambhaviPD doh!  Sorry about that.  You could still look at the other PR and see if you have ideas for how to improve it, based on what you wrote (e.g., would there be value to add your examples/doctests?), if you want.

**Comment by SambhaviPD** [comment]
Sure @adnanhemani and @davidwagner, I shall definitely take a look at #476  and let know.

**Pull request closed without merging**
