### PR TITLE
Change Circle's radius argument to area

### LINKED ISSUE #407: Change all Circle arguments for 'radius' to 'area'
This is to be consistent with how we've been drawing circles everywhere else around the Maps module

### PR DESCRIPTION
**Pull request by adnanhemani**
[N/A] Wrote test for feature (re-ran tests and all pass, including the tests that should trigger a warning now)
[X] Added changes to CHANGELOG.md
[X] Bumped version number (delete if unneeded)

**Changes proposed:**
Closes #407. The reasoning behind this change is also listed in the same PR.

### CODE REVIEW

**Comment by davidwagner** [comment]
Unfortunately there are now some conflicts, and the proper method for merging is not entirely obvious to me.  @adnanhemani , can you update this PR accordingly, and then ping me for another review?  Thanks.

**Comment by davidwagner** [comment]
@adnanhemani  Alas I think I still need help figuring out how to resolve the conflicts on this one... :-(

**Comment by adnanhemani** [comment]
Sorry, missed the previous comment. Working on this now

**Comment by adnanhemani** [comment]
@davidwagner merge conflicts should be resolved! :D

**Review by davidwagner — APPROVED** [review]

**Pull request merged**
