### PR TITLE
Update dependency version numbers

### LINKED ISSUE #328: Update dependencies to specify newer version of setuptools
I think we need to update the version of the `setuptools` package used.  `linux_environment.yml` specifies setuptools 19.6.2, and I think that's causing the Travis build to break.

The Travis build goes awry in running `python3 setup.py install`; it tries to `pip install folium==0.2.1`, which triggers an install of `requests>=1.0.0`, which triggers an install of `docopt>=0.6.1`, which triggers an install of `PyYAML>=3.10`, which triggers an install of `pathlib2>=2.2.0`, which triggers the following error message:

``error: Setup script exited with error in pathlib2 setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in scandir;python_version<"3.5" at ;python_version<"3.5"``

It appears that this is an [environment marker](https://www.python.org/dev/peps/pep-0508/#environment-markers), and I think setuptools 19.6.2 doesn't support environment markers.

I think we need to update the dependencies to use a newer version of setuptools.  setuptools 19.6.2 is a pretty ancient version of setuptools; the current is 40.2.0.  From the [setuptools version logs](https://setuptools.readthedocs.io/en/latest/history.html), it looks like support for environment markers was only added in setuptools 20.5.

In general, a lot of the dependencies in `linux_environment.yml`, `osx_environment.yml`, `readthedocs.yml` are very old (Python 3.4, etc.).  We should probably just update them all.  Also `requirements.txt` specifies folium 0.2.1 and we should probably update that to avoid specifying any version number so we get the latest version of folium.

### PR DESCRIPTION
**Pull request by davidwagner**
**Changes proposed:**
I've updated the dependencies in `linux_environment.yml` and `osx_environment.yml`. Also updated to Python 3.6 in `.travis.yml` and `readthedocs.yml`.  Hopefully this will fix #328, so it builds with Travis.

### CODE REVIEW

**Comment by davidwagner** [comment]
Looks like this does indeed un-break Travis (so now Travis can build again).  It does expose a separate bug (#323).

**Comment by davidwagner** [comment]
BTW, I didn't update the folium dependency; I left that hardcoded at version 0.2.1, because I don't know what the impact of that change might be.

**Comment by papajohn** [comment]
I'm blindly approving this one because I really don't know the consequences, but glad to hear that Travis will work again.

**Comment by SamLau95** [comment]
This seems safe to me - I haven't heard of any breaking updates for the packages we depend on. Having Travis work should give us more peace of mind.

**Pull request merged**
