### PR TITLE
Issue #163: Added documentation for method: stack

### PR DESCRIPTION
**Pull request by SambhaviPD**
#Issue 163: Added documentation for method: stack

### CODE REVIEW

**Comment by SambhaviPD** [comment]
@adnanhemani - Noticed the following in my travis build. Let me try giving tabs directly, I generally use 4 spaces and give a tab.
Shall I close this PR  and open a new one with tab issue fixed ?

    from .tables import *
E     File "/home/travis/build/data-8/datascience/datascience/tables.py", line 1813
E       """ Stacks rows from a table based on key and labels
E                                                          ^
E   TabError: inconsistent use of tabs and spaces in indentation

**Comment by SambhaviPD** [comment]
@adnanhemani - Build failed due to indentation issues. I generally use spaces manually to make a tab, instead I shall use tabs. Should I close this PR and re-open a new one ?

**Comment by adnanhemani** [comment]
@SambhaviPD yes please! Try to adhere to the docstrings that have already been created for all other methods :)

**Comment by SambhaviPD** [comment]
@adnanhemani - sorry about that. Let me close this PR and make sure my code adheres to the docstrings and submit a new PR.

**Pull request closed without merging**
