### PR TITLE
Added some predicates for strings.

### PR DESCRIPTION
**Pull request by henryem**
[\*] Wrote test for feature
[\*] Added note about PR in CHANGELOG.md
[\*] Bumped version number (delete if unneeded)

**Changes proposed:**
Added two predicates for strings in tables: `containing` and `contained_in`.  See #231 .

### CODE REVIEW

**Comment by SamLau95** [comment]
This looks good to me!

**Comment by henryem** [comment]
@SamLau95 can you push this version (0.7.0) to the pypi repo?  We also need to upgrade the data8/ds8 servers.

**Comment by SamLau95** [comment]
@ryanlovett I pushed the version to pypi and updated the systemuser Dockerfile. If you're updating the JHub proxy tonight think you can push this change through too? (I didn't push a new container to DockerHub.)

**Comment by ryanlovett** [comment]
Yes, will do.

Ryan, from my phone

**Comment by ryanlovett** [comment]
Fyi, docker hub is setup to automatically rebuild data8/systemuser when the
Dockerfile changes in the git repo. I'm pulling to the nodes now.


Ryan

**Comment by ryanlovett** [comment]
@SamLau95 I just noticed that you committed the 0.7.0 change to the systemuser master branch whereas the deployments are using the nodrive tag. I just committed the same change to :nodrive and will pull to the nodes after it is built.

**Comment by SamLau95** [comment]
Oops, thanks for the catch!


On September 8, 2016 at 4:24:05 PM, Ryan Lovett (notifications@github.com) wrote:

@SamLau95 I just noticed that you committed the 0.7.0 change to the systemuser master branch whereas the deployments are using the nodrive tag. I just committed the same change to :nodrive and will pull to the nodes after it is built.

**Comment by henryem** [comment]
Can you let us know when the change is available?  A student (one of the few who actually run the textbook examples, apparently) noticed recently that a textbook example that requires 0.7.0 doesn't work.

**Comment by ryanlovett** [comment]
Pulling right now... should be about 5-10 minutes after which students
would need to stop and start their server to get the new image.

**Pull request merged**
