### PR TITLE
Add bar and group_bar interactive functions

### PR DESCRIPTION
**Pull request by khsu2000**
[x] Wrote test for feature
[x] Added changes to CHANGELOG.md

**Changes proposed:**
Addresses #495 and adds `ibar`, `igroup_bar`, and `igroup_barh` functions. Adds additional tests for interactive bar functions.

### CODE REVIEW

**Comment by khsu2000** [comment]
It looks like the `test_read_table` test needs to be updated, since the test tries to read from https://raw.githubusercontent.com/data-8/textbook/gh-pages/data/deflategate.csv, which is a 404 error. Would someone be able to advise/land a PR to fix this test?

**Comment by davidwagner** [comment]
This looks great to me, but I didn't review it carefully.  @adnanhemani would you mind giving this a review, if you have a chance?

**Comment by davidwagner** [comment]
The link to the table should be fixed in PR #505 (now merged).  Thanks for pointing that out.

**Comment by davidwagner** [comment]
Looks great.  Thank you!

**Review by davidwagner — APPROVED** [review]

**Pull request merged**
