### PR TITLE
Histogram labeling and bug fixes

### PR DESCRIPTION
**Pull request by papajohn**
- Fixes x-axis labeling bug for complicated bin sizes
- Y-axis labeled as "percent per unit" with customizable unit
- Yellow on top of blue for prettier overlapping regions

### CODE REVIEW

**Comment by papajohn** [comment]
This change addresses https://piazza.com/class/ijdg22juvgh64x?cid=433

"When I make a histogram of household incomes using the bins provided, the histogram only includes incomes up to 70000. When I check the values in the table they go well above this, though. IS this supposed to happen?

"I think it's just automatically cutting off after the first eight bins. Is there a way to make it show all of them?"

**Comment by SamLau95** [comment]
Thanks John! @cboettig was also asking about this.

**Comment by papajohn** [comment]
Do you mind deploying to data8 & ds8? We'll get more consistent homework submissions if we push soon. Thanks.

**Comment by SamLau95** [comment]
Sure; deploying v0.5.6 now.

**Comment by SamLau95** [comment]
@ryanlovett When I deploy to ds8 it looks like my SSH publickey is missing from nodes 1 and 2.

```
ubuntu@ds8-provisioner:~/jupyterhub-deploy$ ssh -v node1
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /home/ubuntu/jupyterhub-deploy/ssh_config
debug1: /home/ubuntu/jupyterhub-deploy/ssh_config line 9: Applying options for node1
debug1: Hostname has changed; re-reading configuration
debug1: Reading configuration data /home/ubuntu/jupyterhub-deploy/ssh_config
debug1: Connecting to 128.32.42.101 [128.32.42.101] port 22.
debug1: Connection established.
debug1: identity file /home/ubuntu/.ssh/id_rsa type 1
debug1: identity file /home/ubuntu/.ssh/id_rsa-cert type -1
debug1: identity file /home/ubuntu/.ssh/id_dsa type -1
debug1: identity file /home/ubuntu/.ssh/id_dsa-cert type -1
debug1: identity file /home/ubuntu/.ssh/id_ecdsa type -1
debug1: identity file /home/ubuntu/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/ubuntu/.ssh/id_ed25519 type -1
debug1: identity file /home/ubuntu/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.4
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.4 pat OpenSSH_6.6.1* compat 0x04000000
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-md5-etm@openssh.com none
debug1: kex: client->server aes128-ctr hmac-md5-etm@openssh.com none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA 5a:64:cc:e7:6a:82:bd:1e:ac:39:25:02:c4:95:c4:cd
debug1: Host '128.32.42.101' is known and matches the ECDSA host key.
debug1: Found key in /home/ubuntu/.ssh/known_hosts:6
debug1: ssh_ecdsa_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/sam/.ssh/id_rsa
debug1: Authentications that can continue: publickey
debug1: Offering RSA public key: /home/ubuntu/.ssh/id_rsa
debug1: Authentications that can continue: publickey
debug1: Trying private key: /home/ubuntu/.ssh/id_dsa
debug1: Trying private key: /home/ubuntu/.ssh/id_ecdsa
debug1: Trying private key: /home/ubuntu/.ssh/id_ed25519
debug1: No more authentication methods to try.
Permission denied (publickey).
```

3 and 4 work, but I cancelled the rebuild anyway. For reference, here's the output from `ssh node3`:

```
ubuntu@ds8-provisioner:~/jupyterhub-deploy$ ssh -v node3
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /home/ubuntu/jupyterhub-deploy/ssh_config
debug1: /home/ubuntu/jupyterhub-deploy/ssh_config line 17: Applying options for node3
debug1: Hostname has changed; re-reading configuration
debug1: Reading configuration data /home/ubuntu/jupyterhub-deploy/ssh_config
debug1: Connecting to 128.32.42.103 [128.32.42.103] port 22.
debug1: Connection established.
debug1: identity file /home/ubuntu/.ssh/id_rsa type 1
debug1: identity file /home/ubuntu/.ssh/id_rsa-cert type -1
debug1: identity file /home/ubuntu/.ssh/id_dsa type -1
debug1: identity file /home/ubuntu/.ssh/id_dsa-cert type -1
debug1: identity file /home/ubuntu/.ssh/id_ecdsa type -1
debug1: identity file /home/ubuntu/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/ubuntu/.ssh/id_ed25519 type -1
debug1: identity file /home/ubuntu/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.6
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.6 pat OpenSSH_6.6.1* compat 0x04000000
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-md5-etm@openssh.com none
debug1: kex: client->server aes128-ctr hmac-md5-etm@openssh.com none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ECDSA bc:bc:23:cf:dd:fa:95:60:a9:f4:e9:98:52:86:bb:1e
debug1: Host '128.32.42.103' is known and matches the ECDSA host key.
debug1: Found key in /home/ubuntu/.ssh/known_hosts:25
debug1: ssh_ecdsa_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/sam/.ssh/id_rsa
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug1: Authentication succeeded (publickey).
Authenticated to 128.32.42.103 ([128.32.42.103]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.16.0-60-generic x86_64)
...
```

I'm deploying on `data8` right now.

PS: Looks like on `ds8` and on `data8` there are working directory changes that haven't been committed. I didn't pull or stash; I just changed the `datascience` version to `0.5.6` in the singleuser `Dockerfile`. Hope that's okay.

**Pull request merged**
